default_region            = "us-east-1"
docker_username           = "ismashal"
github_username           = "ismashal"
github_project_name       = "ContainerizedApplication"
github_token			  = "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"
app_name                  = "node-aws-fargate-app"
environment               = "staging"
docker_hub_token		  = "9f327b3b-9bee-4988-a548-cc7df9740e20"
